version: "2"
# Version 3 does not support ipv4_address specification as of yet. Do not upgrade without checking for support!

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Zurich'
    volumes:
      - '/home/ubuntu/appdata/pihole/config:/etc/pihole'
      - '/home/ubuntu/appdata/pihole/dnsmasq:/etc/dnsmasq.d'
    #    cap_add:
    #      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)
    networks:
      - dns_net
    restart: unless-stopped

  unbound:
    container_name: unbound
    image: klutchell/unbound:latest
    environment:
      TZ: 'Europe/Zurich'
    networks:
      dns_net:
        ipv4_address: 172.16.238.2
    restart: unless-stopped

networks:
  dns_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
